### ISSUE TITLE
Unable to open "epub" files normally due to problem with "org-roam--file-name-extension"

### ISSUE THREAD

**Issue by sync0** [org-roam/org-roam#1645]
# Description
When trying to open an "epub" file within Emacs (for example, with `counsel-find-file` or `org-ref` custom functions), Emacs does not visit the buffer with the epub. Instead, I get the following error message from `org-roam`:

`org-roam--file-name-extension: Wrong type argument: stringp, nil`

I am using `nov.el` to open epub files in Emacs, but the problem does not seem to be with this package. After getting the aforementioned error message, if I do `C-x b` (`switch-to-buffer`), the epub file appears listed there: I can even open that buffer and navigate it with `nov.el` as I would expect. 

This error does not occur with pdf files: These open normally.

I attempted to open the epub file while visiting a buffer that is not in `org-mode`, but the error persists. 

# Backtrace
![image](https://user-images.githubusercontent.com/16617499/126411801-efce0109-1f28-4814-96b1-74c7449c5bb7.png)

(Sorry, I do not know how to copy output from the debugger. As you can see, the problem does seem to be with the way `org-roam` opens files. Could it be a problem with the predicate function?)

# Expected Results
When opening an epub file, Emacs should open this file in a buffer, and then visit that buffer.

# Actual Results
Emacs does open the epub file, but does not visit that buffer. Instead, Emacs remains in the current buffer and outputs the error message:

`org-roam--file-name-extension: Wrong type argument: stringp, nil`

# Environment
Emacs: GNU Emacs 27.2 
Org: Org mode version 9.4.4
Org-roam: 2.0.0

**Comment by jethrokuan** [comment]
Should've been fixed by #1651, do check back and close the issue if this fixes it for you.

**Comment by sync0** [comment]
Thank you for such quick reply. I checked the debugger, but the issue persists. The backtrace shows the same output as previously.

**Comment by jethrokuan** [comment]
I can't reproduce this anymore. Can you check if you're loading an old byte-compiled version of the `org-roam-file-p` function? There's just no way `org-roam--file-name-extension` is being called with a nil argument anymore.

**Comment by sync0** [comment]
You were right. Thank you so much! Issued closed. Btw, your package is amazing.
