### ISSUE TITLE
(invalid-function (target (org-roam-capture--get :if-new)))

### ISSUE THREAD

**Issue by brabalan** [org-roam/org-roam#1814]
### Description
After updating org-roam, my dailies templates no longer work. I renamed `if-new` to `target` in the templates, to no avail.

#### Steps to Reproduce
- call `(org-roam-dailies-goto-today)`
- choose a template

#### Backtrace
```
Debugger entered--Lisp error: (invalid-function (target (org-roam-capture--get :if-new)))
  (target (org-roam-capture--get :if-new))()
  org-roam-capture--get-if-new-target-a((closure (org-end-time-was-given t) nil "Get the current capture :target for the capture te..." (or (org-roam-capture--get :target) (user-error "Template needs to specify `:target'"))))
  apply(org-roam-capture--get-if-new-target-a (closure (org-end-time-was-given t) nil "Get the current capture :target for the capture te..." (or (org-roam-capture--get :target) (user-error "Template needs to specify `:target'"))) nil)
  org-roam-capture--get-target()
  (let* ((val (org-roam-capture--get-target))) (if (consp val) (let* ((x103 (car val))) (cond ((eq x103 'file) (let* ((x104 ...)) (if (consp x104) (let* ... ...) nil))) ((eq x103 'file+olp) (let* ((x107 ...)) (if (consp x107) (let* ... ...) nil))) ((eq x103 'file+head) (let* ((x112 ...)) (if (consp x112) (let* ... ...) nil))) ((eq x103 'file+head+olp) (let* ((x117 ...)) (if (consp x117) (let* ... ...) nil))) ((eq x103 'file+datetree) (let* ((x124 ...)) (if (consp x124) (let* ... ...) nil))) ((eq x103 'node) (let* ((x129 ...)) (if (consp x129) (let* ... ...) nil))) (t nil))) nil))
  (let (p new-file-p) (let* ((val (org-roam-capture--get-target))) (if (consp val) (let* ((x103 (car val))) (cond ((eq x103 'file) (let* (...) (if ... ... nil))) ((eq x103 'file+olp) (let* (...) (if ... ... nil))) ((eq x103 'file+head) (let* (...) (if ... ... nil))) ((eq x103 'file+head+olp) (let* (...) (if ... ... nil))) ((eq x103 'file+datetree) (let* (...) (if ... ... nil))) ((eq x103 'node) (let* (...) (if ... ... nil))) (t nil))) nil)) (save-excursion (goto-char p) (let* ((node (and t org-roam-capture--node)) (id (and node (progn (or ... ...) (aref node 5))))) (if id (org-entry-put p "ID" id))) (prog1 (org-id-get-create) (run-hooks 'org-roam-capture-new-node-hook))))
  org-roam-capture--setup-target-location()
  (cond ((run-hook-with-args-until-success 'org-roam-capture-preface-hook)) (t (org-roam-capture--setup-target-location)))
  (let ((id (cond ((run-hook-with-args-until-success 'org-roam-capture-preface-hook)) (t (org-roam-capture--setup-target-location))))) (org-roam-capture--adjust-point-for-capture-type) (org-capture-put :template (org-roam-capture--fill-template (org-capture-get :template))) (org-roam-capture--put :id id) (org-roam-capture--put :finalize (or (org-capture-get :finalize) (org-roam-capture--get :finalize))))
  org-roam-capture--prepare-buffer()
  org-capture-set-target-location()
  org-capture-goto-target(nil)
  #f(compiled-function (&optional goto keys) "Capture something.\n\\<org-capture-mode-map>\nThis will let you select a template from `org-capture-templates', and\nthen file the newly captured information.  The text is immediately\ninserted at the target location, and an indirect buffer is shown where\nyou can edit it.  Pressing `\\[org-capture-finalize]' brings you back to the previous\nstate of Emacs, so that you can continue your work.\n\nWhen called interactively with a `\\[universal-argument]' prefix argument GOTO, don't\ncapture anything, just go to the file/headline where the selected\ntemplate stores its notes.\n\nWith a `\\[universal-argument] \\[universal-argument]' prefix argument, go to the last note stored.\n\nWhen called with a `C-0' (zero) prefix, insert a template at point.\n\nWhen called with a `C-1' (one) prefix, force prompting for a date when\na datetree entry is made.\n\nELisp programs can set KEYS to a string associated with a template\nin `org-capture-templates'.  In this case, interactive selection\nwill be bypassed.\n\nIf `org-capture-use-agenda-date' is non-nil, capturing from the\nagenda will use the date at point as the default date.  Then, a\n`C-1' prefix will tell the capture process to use the HH:MM time\nof the day at point (if any) or the current HH:MM time." (interactive "P") #<bytecode 0x1560693fedb9>)((4) nil)
  apply(#f(compiled-function (&optional goto keys) "Capture something.\n\\<org-capture-mode-map>\nThis will let you select a template from `org-capture-templates', and\nthen file the newly captured information.  The text is immediately\ninserted at the target location, and an indirect buffer is shown where\nyou can edit it.  Pressing `\\[org-capture-finalize]' brings you back to the previous\nstate of Emacs, so that you can continue your work.\n\nWhen called interactively with a `\\[universal-argument]' prefix argument GOTO, don't\ncapture anything, just go to the file/headline where the selected\ntemplate stores its notes.\n\nWith a `\\[universal-argument] \\[universal-argument]' prefix argument, go to the last note stored.\n\nWhen called with a `C-0' (zero) prefix, insert a template at point.\n\nWhen called with a `C-1' (one) prefix, force prompting for a date when\na datetree entry is made.\n\nELisp programs can set KEYS to a string associated with a template\nin `org-capture-templates'.  In this case, interactive selection\nwill be bypassed.\n\nIf `org-capture-use-agenda-date' is non-nil, capturing from the\nagenda will use the date at point as the default date.  Then, a\n`C-1' prefix will tell the capture process to use the HH:MM time\nof the day at point (if any) or the current HH:MM time." (interactive "P") #<bytecode 0x1560693fedb9>) ((4) nil))
  (let ((+file-templates-inhibit t)) (apply fn args))
  +file-templates-inhibit-in-org-capture-a(#f(compiled-function (&optional goto keys) "Capture something.\n\\<org-capture-mode-map>\nThis will let you select a template from `org-capture-templates', and\nthen file the newly captured information.  The text is immediately\ninserted at the target location, and an indirect buffer is shown where\nyou can edit it.  Pressing `\\[org-capture-finalize]' brings you back to the previous\nstate of Emacs, so that you can continue your work.\n\nWhen called interactively with a `\\[universal-argument]' prefix argument GOTO, don't\ncapture anything, just go to the file/headline where the selected\ntemplate stores its notes.\n\nWith a `\\[universal-argument] \\[universal-argument]' prefix argument, go to the last note stored.\n\nWhen called with a `C-0' (zero) prefix, insert a template at point.\n\nWhen called with a `C-1' (one) prefix, force prompting for a date when\na datetree entry is made.\n\nELisp programs can set KEYS to a string associated with a template\nin `org-capture-templates'.  In this case, interactive selection\nwill be bypassed.\n\nIf `org-capture-use-agenda-date' is non-nil, capturing from the\nagenda will use the date at point as the default date.  Then, a\n`C-1' prefix will tell the capture process to use the HH:MM time\nof the day at point (if any) or the current HH:MM time." (interactive "P") #<bytecode 0x1560693fedb9>) (4) nil)
  apply(+file-templates-inhibit-in-org-capture-a #f(compiled-function (&optional goto keys) "Capture something.\n\\<org-capture-mode-map>\nThis will let you select a template from `org-capture-templates', and\nthen file the newly captured information.  The text is immediately\ninserted at the target location, and an indirect buffer is shown where\nyou can edit it.  Pressing `\\[org-capture-finalize]' brings you back to the previous\nstate of Emacs, so that you can continue your work.\n\nWhen called interactively with a `\\[universal-argument]' prefix argument GOTO, don't\ncapture anything, just go to the file/headline where the selected\ntemplate stores its notes.\n\nWith a `\\[universal-argument] \\[universal-argument]' prefix argument, go to the last note stored.\n\nWhen called with a `C-0' (zero) prefix, insert a template at point.\n\nWhen called with a `C-1' (one) prefix, force prompting for a date when\na datetree entry is made.\n\nELisp programs can set KEYS to a string associated with a template\nin `org-capture-templates'.  In this case, interactive selection\nwill be bypassed.\n\nIf `org-capture-use-agenda-date' is non-nil, capturing from the\nagenda will use the date at point as the default date.  Then, a\n`C-1' prefix will tell the capture process to use the HH:MM time\nof the day at point (if any) or the current HH:MM time." (interactive "P") #<bytecode 0x1560693fedb9>) ((4) nil))
  org-capture((4) nil)
  (let* ((props (plist-put props :call-location (point-marker))) (org-capture-templates (mapcar #'(lambda (template) (org-roam-capture--convert-template template props)) (or templates org-roam-capture-templates))) (org-roam-capture--node node) (org-roam-capture--info info)) (if (and (not keys) (= (length org-capture-templates) 1)) (progn (setq keys (car (car org-capture-templates))))) (org-capture goto keys))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:goto :keys :node :info :props :templates :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:goto :keys :node ..." (car --cl-keys--)))))) (let* ((props (plist-put props :call-location (point-marker))) (org-capture-templates (mapcar #'(lambda (template) (org-roam-capture--convert-template template props)) (or templates org-roam-capture-templates))) (org-roam-capture--node node) (org-roam-capture--info info)) (if (and (not keys) (= (length org-capture-templates) 1)) (progn (setq keys (car (car org-capture-templates))))) (org-capture goto keys)))
  (let* ((goto (car (cdr (plist-member --cl-rest-- ':goto)))) (keys (car (cdr (plist-member --cl-rest-- ':keys)))) (node (car (cdr (plist-member --cl-rest-- ':node)))) (info (car (cdr (plist-member --cl-rest-- ':info)))) (props (car (cdr (plist-member --cl-rest-- ':props)))) (templates (car (cdr (plist-member --cl-rest-- ':templates))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '...) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:goto :keys :node ..." (car --cl-keys--)))))) (let* ((props (plist-put props :call-location (point-marker))) (org-capture-templates (mapcar #'(lambda ... ...) (or templates org-roam-capture-templates))) (org-roam-capture--node node) (org-roam-capture--info info)) (if (and (not keys) (= (length org-capture-templates) 1)) (progn (setq keys (car (car org-capture-templates))))) (org-capture goto keys))))
  org-roam-capture-(:goto (4) :node #s(org-roam-node :file nil :file-hash nil :file-atime nil :file-mtime nil :id nil :level nil :point nil :todo nil :priority nil :scheduled nil :deadline nil :title nil :properties nil :olp nil :tags nil :aliases nil :refs nil) :templates (("j" "journal" entry "* %<%H:%M> %?" :target (file+head+olp "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d (%A)>\n#+startup: showall\n* Dai..." ("Journal"))) ("t" "do today" item "[ ] %a" :target (file+head+olp "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d (%A)>\n#+startup: showall\n* Dai..." ("Do Today")) :immediate-finish t) ("m" "maybe do today" item "[ ] %a" :target (file+head+olp "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d (%A)>\n#+startup: showall\n* Dai..." ("Maybe Do Today")) :immediate-finish t)) :props (:override-default-time (24873 3148 670062 984000) :call-location #<marker at 1 in 20210707175728-exporting_pdfs_with_annotations_on_remarkable_2.org>))
  (let ((org-roam-directory (expand-file-name org-roam-dailies-directory org-roam-directory))) (org-roam-capture- :goto (if goto (progn '(4))) :node (record 'org-roam-node nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil) :templates org-roam-dailies-capture-templates :props (list :override-default-time time)))
  org-roam-dailies--capture((24873 3148 670062 984000) t)
  org-roam-dailies-capture-today(t)
  org-roam-dailies-goto-today()
  funcall-interactively(org-roam-dailies-goto-today)
  call-interactively(org-roam-dailies-goto-today nil nil)
  command-execute(org-roam-dailies-goto-today)
```

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-26
- Framework: Doom
- Org: Org mode version 9.5 (9.5-b83ae59 @ /home/schmitta/.emacs-configs/doom-emacs/.local/straight/build-27.2/org/)
- Org-roam: v2.1.0-10-gcfabe0e

**Comment by loopdreams** [comment]
I am also having the same issue after running doom upgrade. Was working fine before. Neither the daily capture templates work now, nor the regular org-roam-insert (produces the same error: (invalid-function (target (org-roam-capture--get :if-new)))

**Comment by Wetlize** [comment]
Can someone confirm please, if this fixed with https://github.com/org-roam/org-roam/commit/48a5d017267afb1663a89b619cb37b069b5a283d in place?

**Comment by cobac** [comment]
Hey, **not** fixed for me with 48a5d01. I'm not using doom (but I'm using straight.el and I've re-builded the package) and I'm on 27.2. I'm testing with a simple template:


```elisp

  (setq org-roam-capture-templates '(("d" "default" plain "%?"
                                      :target (file+head "${slug}.org"
                                                         "#+title: ${title}")
                                      :unnarrowed t)))
```


```

Debugger entered--Lisp error: (invalid-function (target (org-roam-capture--get :if-new)))
  (target (org-roam-capture--get :if-new))()
  org-roam-capture--get-if-new-target-a((closure (org-end-time-was-given t) nil "Get the current capture :target for the capture te..." (or (org-roam-capture--get :target) (user-error "Template needs to specify `:target'"))))
  apply(org-roam-capture--get-if-new-target-a (closure (org-end-time-was-given t) nil "Get the current capture :target for the capture te..." (or (org-roam-capture--get :target) (user-error "Template needs to specify `:target'"))) nil)
  org-roam-capture--get-target()
  (let* ((val (org-roam-capture--get-target))) (if (consp val) (let* ((x278 (car val))) (cond ((eq x278 'file) (let* ((x279 ...)) (if (consp x279) (let* ... ...) nil))) ((eq x278 'file+olp) (let* ((x282 ...)) (if (consp x282) (let* ... ...) nil))) ((eq x278 'file+head) (let* ((x287 ...)) (if (consp x287) (let* ... ...) nil))) ((eq x278 'file+head+olp) (let* ((x292 ...)) (if (consp x292) (let* ... ...) nil))) ((eq x278 'file+datetree) (let* ((x299 ...)) (if (consp x299) (let* ... ...) nil))) ((eq x278 'node) (let* ((x304 ...)) (if (consp x304) (let* ... ...) nil))) (t nil))) nil))
  (let (p new-file-p) (let* ((val (org-roam-capture--get-target))) (if (consp val) (let* ((x278 (car val))) (cond ((eq x278 'file) (let* (...) (if ... ... nil))) ((eq x278 'file+olp) (let* (...) (if ... ... nil))) ((eq x278 'file+head) (let* (...) (if ... ... nil))) ((eq x278 'file+head+olp) (let* (...) (if ... ... nil))) ((eq x278 'file+datetree) (let* (...) (if ... ... nil))) ((eq x278 'node) (let* (...) (if ... ... nil))) (t nil))) nil)) (save-excursion (goto-char p) (let* ((node (and t org-roam-capture--node)) (id (and node (progn (or ... ...) (aref node 5))))) (if id (org-entry-put p "ID" id))) (prog1 (org-id-get-create) (run-hooks 'org-roam-capture-new-node-hook))))
  org-roam-capture--setup-target-location()
  (cond ((run-hook-with-args-until-success 'org-roam-capture-preface-hook)) (t (org-roam-capture--setup-target-location)))
  (let ((id (cond ((run-hook-with-args-until-success 'org-roam-capture-preface-hook)) (t (org-roam-capture--setup-target-location))))) (org-roam-capture--adjust-point-for-capture-type) (org-capture-put :template (org-roam-capture--fill-template (org-capture-get :template))) (org-roam-capture--put :id id) (org-roam-capture--put :finalize (or (org-capture-get :finalize) (org-roam-capture--get :finalize))))
  org-roam-capture--prepare-buffer()
  org-capture-set-target-location(nil)
  org-capture(nil "d")
  (let* ((props (plist-put props :call-location (point-marker))) (org-capture-templates (mapcar #'(lambda (template) (org-roam-capture--convert-template template props)) (or templates org-roam-capture-templates))) (org-roam-capture--node node) (org-roam-capture--info info)) (if (and (not keys) (= (length org-capture-templates) 1)) (progn (setq keys (car (car org-capture-templates))))) (org-capture goto keys))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:goto :keys :node :info :props :templates :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:goto :keys :node ..." (car --cl-keys--)))))) (let* ((props (plist-put props :call-location (point-marker))) (org-capture-templates (mapcar #'(lambda (template) (org-roam-capture--convert-template template props)) (or templates org-roam-capture-templates))) (org-roam-capture--node node) (org-roam-capture--info info)) (if (and (not keys) (= (length org-capture-templates) 1)) (progn (setq keys (car (car org-capture-templates))))) (org-capture goto keys)))
  (let* ((goto (car (cdr (plist-member --cl-rest-- ':goto)))) (keys (car (cdr (plist-member --cl-rest-- ':keys)))) (node (car (cdr (plist-member --cl-rest-- ':node)))) (info (car (cdr (plist-member --cl-rest-- ':info)))) (props (car (cdr (plist-member --cl-rest-- ':props)))) (templates (car (cdr (plist-member --cl-rest-- ':templates))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '...) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:goto :keys :node ..." (car --cl-keys--)))))) (let* ((props (plist-put props :call-location (point-marker))) (org-capture-templates (mapcar #'(lambda ... ...) (or templates org-roam-capture-templates))) (org-roam-capture--node node) (org-roam-capture--info info)) (if (and (not keys) (= (length org-capture-templates) 1)) (progn (setq keys (car (car org-capture-templates))))) (org-capture goto keys))))
  org-roam-capture-(:node #s(org-roam-node :file nil :file-hash nil :file-atime nil :file-mtime nil :id nil :level nil :point nil :todo nil :priority nil :scheduled nil :deadline nil :title "fkdjdfkj" :properties nil :olp nil :tags nil :aliases nil :refs nil) :templates nil :props (:finalize find-file :call-location #<marker at 1 in  *mu4e-main*>))
  (if (progn (or (and (memq (type-of node) cl-struct-org-roam-node-tags) t) (signal 'wrong-type-argument (list 'org-roam-node node))) (aref node 1)) (org-roam-node-visit node other-window) (org-roam-capture- :node node :templates templates :props '(:finalize find-file :call-location #<marker at 1 in  *mu4e-main*>)))
  (let ((node (org-roam-node-read initial-input filter-fn))) (if (progn (or (and (memq (type-of node) cl-struct-org-roam-node-tags) t) (signal 'wrong-type-argument (list 'org-roam-node node))) (aref node 1)) (org-roam-node-visit node other-window) (org-roam-capture- :node node :templates templates :props '(:finalize find-file :call-location #<marker at 1 in  *mu4e-main*>))))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:templates :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:templates)" (car --cl-keys--)))))) (let ((node (org-roam-node-read initial-input filter-fn))) (if (progn (or (and (memq (type-of node) cl-struct-org-roam-node-tags) t) (signal 'wrong-type-argument (list 'org-roam-node node))) (aref node 1)) (org-roam-node-visit node other-window) (org-roam-capture- :node node :templates templates :props '(:finalize find-file :call-location #<marker at 1 in  *mu4e-main*>)))))
  (let* ((templates (car (cdr (plist-member --cl-rest-- ':templates))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '...) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:templates)" (car --cl-keys--)))))) (let ((node (org-roam-node-read initial-input filter-fn))) (if (progn (or (and (memq ... cl-struct-org-roam-node-tags) t) (signal 'wrong-type-argument (list ... node))) (aref node 1)) (org-roam-node-visit node other-window) (org-roam-capture- :node node :templates templates :props '(:finalize find-file :call-location #<marker at 1 in  *mu4e-main*>))))))
  org-roam-node-find()
  funcall-interactively(org-roam-node-find)
  call-interactively(org-roam-node-find nil nil)
  command-execute(org-roam-node-find)

```

**Comment by loopdreams** [comment]
Can also confirm that [`48a5d01`](https://github.com/org-roam/org-roam/commit/48a5d017267afb1663a89b619cb37b069b5a283d) didn't seem to fix it.

For now, I'm using the `advice-remove` line suggested by @brabalan and this works for me (provided `if-new` is replaced by `target` in the templates, which it seems is now the preferred syntax anyway?)

**Comment by Wetlize** [comment]
If someone still uses the workaround published by @brabalan, then it shouldn't be needed anymore and can be removed.

**Comment by brabalan** [comment]
I confirm it works. Thanks!
