### ISSUE TITLE
Links displayed in literal form in org-roam buffers 

### ISSUE THREAD

**Issue by ahmed-shariff** [org-roam/org-roam#2198]
### Description
Links in the org-roam buffer are displayed in the literal form (see image below).

#### Steps to Reproduce
Run emacs with `-Q` with straight bootstrapped.
```sh
emacs -Q -l ~/.emacs.d/straight/repos/straight.el/bootstrap.el
```
Run the following:
```emacs-lisp
(straight-use-package 'org)
(straight-use-package 'org-roam)

(setq org-roam-directory (file-truename "~/temp/org-roam-test/"))
(setq org-roam-node-display-template (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
(org-roam-db-autosync-mode)

(with-eval-after-load 'org-roam
  (message "Tests running")
  (dolist (f (directory-files (file-truename "~/temp/org-roam-test/"))) (unless (member f '("." "..")) (delete-file f)))
  (delete-directory (file-truename "~/temp/org-roam-test/") t)
  (make-directory (file-truename "~/temp/org-roam-test/"))
  (with-current-buffer (find-file-noselect (file-truename "~/temp/org-roam-test/test.org"))
    (erase-buffer)
    (insert "* test 1
:PROPERTIES:
:ID:       155f6464-92a7-4fb0-bd56-cb451b1a57f9
:END:

* test 2
:PROPERTIES:
:ID:       7e5a8c18-34a8-4584-8a27-b5273c2c3b66
:END:
[[id:155f6464-92a7-4fb0-bd56-cb451b1a57f9][test 1]]")
    (save-buffer))
  
  (org-id-goto "155f6464-92a7-4fb0-bd56-cb451b1a57f9")
  (org-roam-db-clear-all)
  (ignore-errors (org-roam-db-sync))
  (ignore-errors (org-roam-db-sync))
  (org-roam-bufffer-toggle))
```
#### Expected Results
Links should be displayed in descriptive form

#### Actual Results
Links displayed in literal form:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/15046660/169177406-6e7ff917-94ec-4efc-8829-f7583a461e27.png">

### Environment
- Emacs: GNU Emacs 27.2 (build 1, x86_64-w64-mingw32)
 of 2021-03-26
- Framework: N/A
- Org: Org mode version 9.5.3 (9.5.3-g5766dd @ c:/Users/amsha/.emacs.d/straight/build/org/)
- Org-roam: v2.2.1-6-g9eaf91b

**Comment by salutis** [comment]
I have this problem too:

<img width="872" alt="Screen Shot 2022-05-20 at 09 00 39" src="https://user-images.githubusercontent.com/1158274/169471686-9b70a3ff-c247-4cf2-9a2e-6b84b2fcd571.png">

**Comment by salutis** [comment]
@ahmed-shariff 

> [...] in the literal form (see image below).

FYI, Org calls this "descriptive" form.  See, e.g. the `org-descriptive-links` variable.

**Comment by salutis** [comment]
@ahmed-shariff 

> FYI, Org calls this "descriptive" form.  See, e.g. the `org-descriptive-links` variable.

Upon reading a bit more, I take this back.  I had it backwards! 😄

**Comment by ahmed-shariff** [comment]
> @ahmed-shariff 
> 
> > FYI, Org calls this "descriptive" form.  See, e.g. the `org-descriptive-links` variable.
> 
> Upon reading a bit more, I take this back.  I had it backwards! 😄 

Lol I think I spent more time trying to figure this out than the issue itself, and I am still not convinced I got it right 😂

**Comment by ahmed-shariff** [comment]
For what it's worth, I'm modifying the `org-roam-preview-function` to display the links in a literal-ish form:

```emacs-lisp
  (defun amsha/org-roam-preview-function ()
    "Same as `org-roam-preview-default-function', but replaces org-roam links to literal-ish form."
    (let ((beg (save-excursion
                 (org-roam-end-of-meta-data t)
                 (point)))
          (end (save-excursion
                 (org-next-visible-heading 1)
                 (point))))
      (s-replace-regexp "\\[id:\\([a-z]\\|[0-9]\\)\\{8\\}-\\([a-z]\\|[0-9]\\)\\{4\\}-\\([a-z]\\|[0-9]\\)\\{4\\}-\\([a-z]\\|[0-9]\\)\\{4\\}-\\([a-z]\\|[0-9]\\)\\{12\\}\\]"
                        ""
                        (string-trim (buffer-substring-no-properties beg end)))))
```

**Comment by dcommisso** [comment]
Same problem here. Something is broken with the last releases of org-mode. The problem is only present when using straight, since straight compiles the last available release (while elpa uses the last stable).

My workaround is to pin org-mode package to the last stable commit (`69c588947d1be9bca1eb8c773f2a8ff117d264ba`) using the official (ugly) straight [hack](https://github.com/radian-software/straight.el#how-do-i-pin-package-versions-or-use-only-tagged-releases)

This is the minimum working configuration:
```
;; Tell straight.el about the profiles we are going to be using.
(setq straight-profiles
      '((nil . "default.el")
        ;; Packages which are pinned to a specific commit.
        (pinned . "pinned.el")))

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(autoload #'straight-x-pull-all "straight-x")
(autoload #'straight-x-freeze-versions "straight-x")

(let ((straight-current-profile 'pinned))
  (straight-use-package 'org)
  (straight-use-package 'org-roam)
  ;; Pin org-mode version.
  (add-to-list 'straight-x-pinned-packages
               '("org" . "69c588947d1be9bca1eb8c773f2a8ff117d264ba")))
```

(finally you have to run `straight-x-freeze-versions` and `straight-x-pull-all` to make straight install the right version)

**Comment by salutis** [comment]
This now works correctly in 2.2.2.  Anyone?

**Comment by gmcninch** [comment]
I'm still seeing this issue. I just deleted ~/.emacs.d/straight, reinstalled everything, and still see the problem,
with org-roam 2.2.2.

org-version ==> 9.5.4
org-mode-version

**Comment by jethrokuan** [comment]
This is usually caused by Org loading midway, or some error occurring in between, so I would first check for that (remove the `ignore-errors`?

**Comment by gmcninch** [comment]
Thanks for the response @jethrokuan . 
I have to confess that yesterday when I commented, I just meant that I was still seeing unformatted links in the *org-roam* buffer; I hadn't yet tried the OPs example, but I have now.

Installation of `org` and `org-roam` via `straight` currently results -- for me, at least -- in the behavior the OP reported.

However, starting from a "sandboxed emacs" (`emacs -Q`), I did the following:
- install `straight.el`
- install `package.el`
- install `org` via `package.el` (version 9.5.4 from `elpa.gnu.org`)
- install `org-roam` via `straight.el`
-  ran the code-snippet of the OP (creating the `test 1` and `test 2` nodes, and calling `org-roam-buffer-toggle`)

In this case, the back-links in the `*org-roam*` buffer **are** rendered correctly.

I guess this suggests the issue involves a difference between the 9.5.4 version of `org` found currently in the `github repo` and the 9.5.4 version on `elpa.gnu.org`.

(I note that when `straight.el` installs `org-roam`, it also installs `org`, from github. But apparently the pre-existence of the `elpa.gnu.org` version of `org` is enough to make things work?)

I don't really know how to try to find the issue, because right now I can't really work out what code renders the links in `*org-buffer*`. I guess it is somehow inherited from `org-mode` but I'm not very familiar with the code...)

**Comment by dlukes** [comment]
I tried running `org-toggle-link-display` with debug enabled and this is the traceback that I got:

```
Debugger entered--Lisp error: (error "org-link is not a valid folding spec")
  error("%s is not a valid folding spec" org-link)
  org-fold-core-set-folding-spec-property(org-link :visible t)
  org-link-descriptive-ensure()
  org-toggle-link-display--text-properties()
  org-toggle-link-display()
  funcall-interactively(org-toggle-link-display)
  command-execute(org-toggle-link-display record)
  execute-extended-command(nil "org-toggle-link-display" nil)
  funcall-interactively(execute-extended-command nil "org-toggle-link-display" nil)
  command-execute(execute-extended-command)
```

So it seems like some conflict with folding? Which also alerted me to the fact that folding doesn't work as well as it did before. In Doom, `zm` used to collapse all backlinks and leave only their headings, but now even the headings disappear.

And now that I look at it, the contents of the backlink buffer is jumbled up in many ways, headings in the wrong places w.r.t. contents, the heading **Backlinks** itself is towards the end of the buffer, whereas it should be at the beginning...

**Comment by dlukes** [comment]
> And now that I look at it, the contents of the backlink buffer is jumbled up in many ways

After a bit more testing, this only seems to be the case when I open the first node after startup. Not sure what's causing the issue, but switching to a different node and back fixes it.

I tried to bisect the link display issue and this is what I came up with (commit hashes refer to the Org Mode repo) -- chronologically in the commit history:

- `release_9.5.4`: links look fine
- (some commits elided)
- `ffdc50842`: links still look fine
- `d72ac89c7..d048c153d`: more serious errors during Org init, mostly empty backlinks buffer
- `fa7530c7b`: links look fine
- `77aa9be5a`: links are displayed in literal form

The commit message for `77aa9be5a` says "Implement overlay- and text-property-based versions of some functions".

**Comment by sillygod** [comment]
My temporary workaround for this is to change the implementation of `org-roam-fontify-link-in-org-mode` like below

```emacs-lisp
(defun org-roam-fontify-like-in-org-mode (s)
  "Fontify string S like in Org mode.
Like `org-fontify-like-in-org-mode', but supports `org-ref'."
  ;; NOTE: pretend that the temporary buffer created by `org-fontify-like-in-org-mode' to
  ;; fontify a `cite:' reference has been hacked by org-ref, whatever that means;
  ;;
  ;; `org-ref-cite-link-face-fn', which is used to supply a face for `cite:' links, calls
  ;; `hack-dir-local-variables' rationalizing that `bibtex-completion' would throw some warnings
  ;; otherwise.  This doesn't seem to be the case and calling this function just before
  ;; `org-font-lock-ensure' (alias of `font-lock-ensure') actually instead of fixing the alleged
  ;; warnings messes the things so badly that `font-lock-ensure' crashes with error and doesn't let
  ;; org-roam to proceed further. I don't know what's happening there exactly but disabling this hackery
  ;; fixes the crashing.  Fortunately, org-ref provides the `org-ref-buffer-hacked' switch, which we use
  ;; here to make it believe that the buffer was hacked.
  ;;
  ;; This is a workaround for `cite:' links and does not have any effect on other ref types.
  ;;
  ;; `org-ref-buffer-hacked' is a buffer-local variable, therefore we inline
  ;; `org-fontify-like-in-org-mode' here
  (with-temp-buffer
    (insert s)
    (let ((org-ref-buffer-hacked t))
      (org-mode)
      (org-font-lock-ensure)
      (if org-link-descriptive
          (org-link-display-format (buffer-string))
      (buffer-string)))))


```

**Comment by dlukes** [comment]
Just FYI (crossposting from #2228), this is apparently fixed by #2236.

**Comment by jackbaty** [comment]
Using a fresh install of Doom Emacs, Org 9.6, and latest Org-roam (7f453f3), this issue is still happening for me. (Links in org-roam buffer are displayed as `[[id:1234][title of link]]`). Wondering if there's anything else I should be doing. Note that if I pin Org to 9.5.3 the links are displayed correctly.

**Comment by dlukes** [comment]
Hmm, same here. If I understand correctly, what #2236 was trying to do was precisely to avoid the need to override `org-fold-core-style` to `'overlays` globally. But it doesn't seem to work.

**Comment by zot** [comment]
I'm getting an error and the org-roam-buffer links don't work:
```
org-roam-fontify-like-in-org-mode: Symbol’s function definition is void: org-font-lock-ensure
```
If I define the `org-font-lock-ensure` alias above, I don't get the error and the links work (and there's more stuff in the org roam buffer).

Maybe the alias needs to be added into `org-roam-utils.el`?

**Comment by tjstankus** [comment]
@jackbaty I hit the same issue with cycling and it was resolved by putting that setting in the `after! org` hook of my doom emacs config. I'm not sure what the solution is if you're not using doom.

**Comment by phrac** [comment]
> > @jackbaty I hit the same issue with cycling and it was resolved by putting that setting in the `after! org` hook of my doom emacs config. I'm not sure what the solution is if you're not using doom.
> 
> That's a great thought. I am using Doom, but for some reason, it doesn't seem to matter when/where I set `org-fold-core-style`, it still breaks org-cycle for me. Thanks for the idea, though!

I am also having the same problem. Setting `org-fold-core-style` anywhere breaks org-cycle. I am using Doom as well.

**Comment by rakoenig** [comment]
> Update: Adding `(setq org-fold-core-style “overlays”)` fixes the problem for me in Org 9.6.

Tried this, links in the org-roam window are working fine now. The only problem is that now in my org system the cycling through the views does not work anymore, as long as this setting is there....

**Comment by WouterSpekkink** [comment]
> Another update: `(setq org-fold-core-style 'overlays)` works for displaying links correctly in org-roam buffers, but it prevents org-cycle from working correctly elsewhere in org-mode. This is odd because most references to problems with cycling claim that setting the style to "overlays" _fixes_ problems with cycling. In my case, specifically, closing (folding) headings works when hitting TAB, but then they will not open (unfold?) by TAB-ing again. So currently I can either have nice links in Org-roam or proper cycling in Org files, but not both.

Same here. Also, while trying to find out more about this `org-fold-core-style` behaviour, I found [this](https://mail.gnu.org/archive/html/emacs-orgmode/2022-05/msg00813.html) discussion. See especially these lines:
"Strictly speaking, I can simplify the 'overlays option to work exactly like the old backend, but it will also require changing some other defaults, which is awkward. Also, it will discourage non-complying packages to keep using outline.el and instead ask users to change to the old backend. I would prefer to avoid this.

'overlays option is intended to be a emergency solution for people experiencing major issues with the new folding mechanism. It will be eventually removed."

In my humble opinion, a fix for the issue with the links should avoid setting `org-fold-core-style` to "overlays", since this is an emergency solution that will be unavailable in the long run.

**Comment by ParetoOptimalDev** [comment]
See my comment mentioned above and if `(font-lock-flush)` solves this issue for you. If so, adding it to the right hook might be a workaround.

**Comment by lazzalazza** [comment]
None of the solutions hereby presented work for me (under spacemacs) but @sillygod 's workaround. I'm using spacemacs and changing `org-fold-core-style` to `'overlays` works for the specific org-roam issue but prevents the correct functioning of org-cycle as in the case of @jackbaty .

**Comment by yantar92** [comment]
Please note that `org-fold-core-style` must be set _before_ loading org. See the docstring.

Re: fontification problems. Org now uses folding to hide invisible link parts. Folding is designed to work only in Org buffers - universal 'invisible text property is no longer used. Consider using `org-copy-visible` or setting org-fold in the target buffer to replicate the Org's text look.

**Comment by lazzalazza** [comment]
Thanks @yantar92 : setting `org-fold-core-style` to `'overlays` in Spacemacs' `dotspacemacs/user-init`, so before loading the org layer, totally solved the issue for me.

**Comment by hwiorn** [comment]
Do you use Emacs 28.x and doomemacs? Check the bytecode of `org-roam-utils.el`.

1. cd `~/.emacs.d/.local/straight/build-*/org-roam`
2. `strings org-roam-utils.elc | grep org-fold-core-style`
    - If the `org-fold-core-style` exists, it will work.

Evaluate below code. If you still see the descriptive form of the link, `org-roam-utils.elc` doesn't have `org-fold-core-style`.
```elisp
(let ((buf (get-buffer-create "*test-org-roam-link*")))
  (with-current-buffer buf
    (delete-region (point-min) (point-max))
    (insert (org-roam-fontify-like-in-org-mode "[[id:a586b43b-c89c-4e60-99e8-17b89e1529fe][Test test node]]")))
  (pop-to-buffer buf))
```

Strangely, Emacs 28.x and `doom sync` optimize `org-fold-core-style` in `let` binding. So it needs to change `let` to `setq-local`. Removing `org-roam-utils.elc` simply can be a workaround.

**Comment by vantu5z** [comment]
Seems it started again.

**Comment by hwiorn** [comment]
@vantu5z
Could you provide more infomation about it?
- What is your distro?
- Emacs version, org-roam, org version and etc.
- `M-x doom/info`

And could you try to use fresh doom-emacs without any custom configurations?

```sh
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
vi ~/.config/doom/init.el # Add +roam2 in org
~/.config/emacs/bin/doom sync
```

I tested Emacs 28.2(73da6d4ad) and fresh doom-emacs(v3.0.0-pre 4e105a9). This issue doesn't seem to appear.

```
Doom loaded 159 packages across 31 modules in 0.411s
GNU Emacs     v28.2            73da6d4ad5750e73767401740f282be272831c3e
Doom core     v3.0.0-pre       grafted, HEAD -> master, origin/master, origin/HEAD 4e105a9 2023-03-22 18:29:38 -0400
Doom modules  v23.03.0-pre     grafted, HEAD -> master, origin/master, origin/HEAD 4e105a9 2023-03-22 18:29:38 -0400
```
